package csg;

/**
 * This class provides the properties that are needed to be loaded for
 * setting up To Do List Maker workspace controls including language-dependent
 * text.
 * 
 * @author Richard McKenna
 * @version 1.0
 */
public enum CSGPropertyType {

    /* THESE ARE THE NODES IN OUR APP */
    // FOR SIMPLE OK/CANCEL DIALOG BOXES
    OH_OK_PROMPT,
    OH_CANCEL_PROMPT,

    // THESE ARE FOR TEXT PARTICULAR TO THE APP'S WORKSPACE CONTROLS
    OH_LEFT_PANE,
    OH_TAS_HEADER_PANE,
    OH_TAS_HEADER_LABEL,
    OH_GRAD_UNDERGRAD_TAS_PANE,
    OH_ALL_RADIO_BUTTON,
    OH_GRAD_RADIO_BUTTON,
    OH_UNDERGRAD_RADIO_BUTTON,
    OH_TAS_HEADER_TEXT_FIELD,
    OH_TAS_TABLE_VIEW,
    OH_NAME_TABLE_COLUMN,
    OH_EMAIL_TABLE_COLUMN,
    OH_SLOTS_TABLE_COLUMN,
    OH_TYPE_TABLE_COLUMN,

    OH_ADD_TA_PANE,
    OH_NAME_TEXT_FIELD,
    OH_EMAIL_TEXT_FIELD,
    OH_ADD_TA_BUTTON,

    OH_RIGHT_PANE,
    OH_OFFICE_HOURS_HEADER_PANE,
    OH_OFFICE_HOURS_HEADER_LABEL,
    OH_OFFICE_HOURS_TABLE_VIEW,
    OH_START_TIME_TABLE_COLUMN,
    OH_END_TIME_TABLE_COLUMN,
    OH_MONDAY_TABLE_COLUMN,
    OH_TUESDAY_TABLE_COLUMN,
    OH_WEDNESDAY_TABLE_COLUMN,
    OH_THURSDAY_TABLE_COLUMN,
    OH_FRIDAY_TABLE_COLUMN,
    OH_DAYS_OF_WEEK,
    OH_FOOLPROOF_SETTINGS,
    
    // FOR THE EDIT DIALOG
    OH_TA_EDIT_DIALOG,
    OH_TA_DIALOG_GRID_PANE,
    OH_TA_DIALOG_HEADER_LABEL, 
    OH_TA_DIALOG_NAME_LABEL,
    OH_TA_DIALOG_NAME_TEXT_FIELD,
    OH_TA_DIALOG_EMAIL_LABEL,
    OH_TA_DIALOG_EMAIL_TEXT_FIELD,
    OH_TA_DIALOG_TYPE_LABEL,
    OH_TA_DIALOG_TYPE_BOX,
    OH_TA_DIALOG_GRAD_RADIO_BUTTON,
    OH_TA_DIALOG_UNDERGRAD_RADIO_BUTTON,
    OH_TA_DIALOG_OK_BOX,
    OH_TA_DIALOG_OK_BUTTON, 
    OH_TA_DIALOG_CANCEL_BUTTON,
    
    TAB_HEADER_BOX,
    TAB_PANE,
    TAB_SITE,
    TAB_SYLLABUS,
    TAB_MEETING_TIMES,
    TAB_OFFICE_HOURS,
    TAB_SCHEDULE,
    
    START_TIME_COMBO_BOX,
    END_TIME_COMBO_BOX,
    COMBO_BOX_HBOX,
    START_TIME_LABEL,
    END_TIME_LABEL,
    
    //SITE COMPONENTS
    SITE_BANNER,
    SITE_BANNER_BOX,
    SITE_PAGES,
    SITE_PAGES_BOX,
    SITE_STYLE,
    SITE_STYLE_BOX,
    SITE_INSTRUCTOR,
    SITE_INSTRUCTOR_BOX,
    
    ADD_LECTURE_BUTTON,
    REMOVE_LECTURE_BUTTON,
    
    ADD_REC_BUTTON,
    REMOVE_REC_BUTTON,
    
    ADD_LAB_BUTTON,
    REMOVE_LAB_BUTTON,
    
    LECTURE_GRIDPANE,
    REC_GRIDPANE,
    LAB_GRIDPANE,
    
    LECTURE_VBOX,
    REC_VBOX,
    LAB_VBOX,
    
    SCHEDULE_NOTE,
    
    REMOVE_SCHEDULE_BUTTON,
    SCHEDULE_TABLE_GRIDPANE,
    
    //PAGES COMPONENTS
    PAGES_HBOX,
    BANNER_GRIDPANE,
    
    
    //STYLES COMPONENT
    STYLES_GRIDPANE,
    STYLES_FAVICON,
    STYLES_NAVBAR,
    STYLES_LEFT,
    STYLES_RIGHT,
    STYLES_CSS_LABEL,
    STYLES_COMBO,
    STYLES_WARNING,
    FAVICON_IV,
    NAVBAR_IV,
    LEFT_IV, RIGHT_IV,
    
    //INSTRUCTOR COMPONENTS
    INSTRUCTOR_GRIDPANE,
    INSTRUCTOR_LABEL,
    INS_OH_BT,
    
    BANNER_SUBJECT, BANNER_NUMBER, BANNER_SEMESTER, BANNER_YEAR, BANNER_TITLE, BANNER_EXPORT,BANNER_TITLE_TEXTFIELD,
    BANNER_SUBJECT_CBOX, BANNER_NUMBER_CBOX, BANNER_SEMESTER_CBOX, BANNER_YEAR_CBOX, BANNER_TITLE_CBOX, BANNER_EXPORT_LABEL,
    PAGES_HOME, PAGES_SYLLABUS, PAGES_SCHEDULE, PAGES_HOMEWORK,
    STYLE_FAVICON, STYLE_NAVBAR, STYLE_LEFT, STYLE_RIGHT,
    INSTRUCTOR_NAME, INSTRUCTOR_ROOM, INSTRUCTOR_EMAIL, INSTRUCTOR_HOME_PAGE,
    INSTRUCTOR_OFFICEHOURS, INSTRUCTOR_OH_TEXTAREA,
    INS_NAME_TF, INS_ROOM_TF, INS_EMAIL_TF, INS_HOMEPAGE_TF, 
    
    //SYLLABUS
    DESCRIPTION_LABEL, DESCRIPTION_TEXTAREA,
    TOPICS_LABEL, TOPICS_TEXTAREA,
    PREREQ_LABEL, PREREQ_TEXTAREA,
    OUTCOME_LABEL, OUTCOME_TEXTAREA,
    TEXTBOOK_LABEL, TEXTBOOK_TEXTAREA,
    GRADED_COMP_LABEL, GRADED_COMP_TEXTAREA,
    GRADING_NOTE_LABEL, GRADING_NOTE_TEXTAREA,
    ACADEMIC_DISHONESTY_LABEL, ACADEMIC_DISHONESTY_TEXTAREA,
    SPECIAL_ASSISTANCE_LABEL, SPECIAL_ASSISTANCE_TEXTAREA,

    //MEETING TIMES
    LECTURES_LABEL, LABS_LABEL, RECITATION_LABEL,
    //LECTURES
    SECTION_LEC, DAYS_LEC, TIME_LEC, ROOM_LEC, LECTURES_TABLE,
    //RECITATION
    SECTION_REC, ROOM_REC, DAYS_TIME_REC, TA1_REC, TA2_REC, RECITATION_TABLE,
    //LABS
    SECTION_LABS, ROOM_LABS, DAYS_TIME_LABS, TA1_LABS, TA2_LABS, LABS_TABLE,
    
    
    //SCHEDULE
    CALENDAR_GRIDPANE,
    CALENDAR_BOUNDARIES_LABEL,
    STARTING_MONDAY, ENDING_FRIDAY,
    CB_SM_DATEPICKER, CB_EF_DATEPICKER,
    
    SCHEDULE_ITEMS, TYPE, DATE, TITLE, TOPIC, ADD_EDIT_LABEL,
    D_TYPE, D_DATE, D_TIME, D_TITLE, D_TOPIC, D_LINK, ADD_UPDATE_BUTTON, CLEAR_BUTTON,
    SCHEDULE_ITEMS_TABLE, D_TYPE_COMBO, D_DATE_DATEPICKER,
    D_TITLE_TEXTFIELD, D_TOPIC_TEXTFIELD, D_LINK_TEXTFIELD,
    
    
    // THESE ARE FOR ERROR MESSAGES PARTICULAR TO THE APP
    OH_NO_TA_SELECTED_TITLE, OH_NO_TA_SELECTED_CONTENT,
    
    CHOOSE_IMAGE_TITLE, INVALID_IMAGE_FILE_TITLE, INVALID_IMAGE_FILE_CONTENT
    
    
}